@echo off
echo Starting MQTTOPCUAServer.exe...
start /wait MQTTOPCUAServer.exe
echo Starting MQTTOPCUAClient.exe...
start /wait MQTTOPCUAClient.exe
echo Starting OPCUAClientGCode.exe...
start /wait OPCUAClientGCode.exe
echo All programs have been started.
