@echo off
echo Closing OPCUAClientGCode.exe...
taskkill /im OPCUAClientGCode.exe /f
echo Closing MQTTOPCUAClient.exe...
taskkill /im MQTTOPCUAClient.exe /f
echo Closing MQTTOPCUAServer.exe...
taskkill /im MQTTOPCUAServer.exe /f
echo All specified processes have been closed.
